[package]
name = "demise-rust"
version = "0.1.0"
authors = ["Christopher Fu <chrisf1337@gmail.com>"]

[dependencies]
unicode-segmentation = "*"
byteorder = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
